# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python base image with hatchling for building
FROM python:3.11-slim as builder

# Set work directory
WORKDIR /app

# Install build system and build tools
RUN pip install hatchling build

# Copy project files
COPY pyproject.toml README.md /app/
COPY src /app/src

# Build the project wheel
RUN python -m build

# Use a separate environment for the final image
FROM python:3.11-slim

WORKDIR /app

# Copy the built wheel from builder stage
COPY --from=builder /app/dist/*.whl /app/

# Install the package
RUN pip install /app/*.whl

# Add debugging info
RUN pip show mcp-server-reddit

# Define default command with verbose output
ENTRYPOINT ["python", "-m", "mcp_server_reddit", "stdio"]
